app_version: 1.1.0-preview.1
behavior_configs:
- base_move_speed: 4.5
  base_wheel_speed: 16.0
  default_mouse_action: click
  free_mode_after_move: false
  free_mode_auto_off_s: 100
  grid_action_level: subgrid
  hide_cursor_on_click: false
  hide_location: bottom_left
  initial_action_location: system_cursor
  initial_overlay_monitor: last_used
  label_chars: ASDFGHJKL
  modifier_tap_mask_key: auto
  mouse_value_cycle_behavior: once
  move_duration_ms: 100
  move_real_cursor_with_virtual: false
  move_speed_multiplier: 4.0
  movement_easing: 0.55
  multi_action_timeout_ms: 400
  name: main_behavior
  send_escape_after_global_alt_tap__windows: true
  tap_threshold_ms: 180
  wheel_easing: 0.3
  wheel_speed_multiplier: 5.0
  wheel_step_size: 100.0
  wheel_step_size_large: 500.0
classname: AppConfig
custom_actions: []
custom_monitor_assignments: []
custom_mouse_scaling: 1.0
custom_mouse_screen_offset_scaling: 1.0
custom_overlay_scaling: 1.0
debug_options: {}
display_input: none
event_tap_location: hid_head
excluded_input_devices: []
general_settings:
  app_window_theme: system
  automatically_check_for_updates: true
  check_for_preview_releases: true
  has_enabled_accessibility_for_label_mode__linux: false
  hide_welcome_screen: true
  ignore_update_to_version: ''
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: QWFPB JLUY' ARSTG MNEIO ZXCDV KH,./
    num_cells_x: 10
    num_cells_y: 1
  - border_width: 1.0
    callback: build_cell_strings
    keys: QWFPB JLUY' ARSTG MNEIO ZXCDV KH,./
    num_cells_x: 1
    num_cells_y: 26
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
  hold_subgrid_key_for_nudge: false
  name: position_based_columns
  nudges_per_cell: 16
  reverse_level_2_keys_on_right: false
  strategy: subgrid
  subgrid_cols: 10
  subgrid_mouse_action_keys: QWFPB JLUY' ARSTG MNEIO ZXCDV KH,./
  subgrid_rows: 3
keyboard_layout:
  code_to_char:
    ArrowDown: "\x1F"
    ArrowLeft: "\x1C"
    ArrowRight: "\x1D"
    ArrowUp: "\x1E"
    AudioVolumeUp:
    - "\x1F"
    - '='
    Backquote:
    - '`'
    - '~'
    Backslash:
    - \
    - '|'
    Backspace: "\b"
    BracketLeft:
    - '['
    - '{'
    BracketRight:
    - ']'
    - '}'
    Comma:
    - ','
    - <
    ContextMenu: "\x10"
    Delete: "\x7F"
    Digit0:
    - '0'
    - )
    Digit1:
    - '1'
    - '!'
    Digit2:
    - '2'
    - '@'
    Digit3:
    - '3'
    - '#'
    Digit4:
    - '4'
    - $
    Digit5:
    - '5'
    - '%'
    Digit6:
    - '6'
    - ^
    Digit7:
    - '7'
    - '&'
    Digit8:
    - '8'
    - '*'
    Digit9:
    - '9'
    - (
    End: "\x04"
    Enter: "\r"
    Equal:
    - '='
    - +
    Escape: "\e"
    F1: "\x10"
    F10: "\x10"
    F11: "\x10"
    F12: "\x10"
    F13: "\x10"
    F14: "\x10"
    F15: "\x10"
    F16: "\x10"
    F2: "\x10"
    F3: "\x10"
    F4: "\x10"
    F5: "\x10"
    F6: "\x10"
    F7: "\x10"
    F8: "\x10"
    F9: "\x10"
    Home: "\x01"
    Insert: "\x05"
    IntlBackslash:
    - "\xA7"
    - "\xB1"
    KeyA:
    - a
    - A
    KeyB:
    - b
    - B
    KeyC:
    - c
    - C
    KeyD:
    - d
    - D
    KeyE:
    - e
    - E
    KeyF:
    - f
    - F
    KeyG:
    - g
    - G
    KeyH:
    - h
    - H
    KeyI:
    - i
    - I
    KeyJ:
    - j
    - J
    KeyK:
    - k
    - K
    KeyL:
    - l
    - L
    KeyM:
    - m
    - M
    KeyN:
    - n
    - N
    KeyO:
    - o
    - O
    KeyP:
    - p
    - P
    KeyQ:
    - q
    - Q
    KeyR:
    - r
    - R
    KeyS:
    - s
    - S
    KeyT:
    - t
    - T
    KeyU:
    - u
    - U
    KeyV:
    - v
    - V
    KeyW:
    - w
    - W
    KeyX:
    - x
    - X
    KeyY:
    - y
    - Y
    KeyZ:
    - z
    - Z
    Lang1: "\x10"
    Lang2: "\x10"
    Minus:
    - '-'
    - _
    NumLock: "\e"
    Numpad0: '0'
    Numpad1: '1'
    Numpad2: '2'
    Numpad3: '3'
    Numpad4: '4'
    Numpad5: '5'
    Numpad6: '6'
    Numpad7: '7'
    Numpad8: '8'
    Numpad9: '9'
    NumpadAdd: +
    NumpadDecimal: .
    NumpadDivide: /
    NumpadEnter: "\x03"
    NumpadEqual: '='
    NumpadMultiply: '*'
    NumpadSubtract: '-'
    PageDown: "\f"
    PageUp: "\v"
    Period:
    - .
    - '>'
    Quote:
    - ''''
    - '"'
    Semicolon:
    - ;
    - ':'
    Slash:
    - /
    - '?'
    Space: ' '
    Tab: "\t"
  id: com.apple.keylayout.US
  name: U.S.
keymaps:
- entries:
    back click: null
    back mouse button: null
    back mouse button (w/o overlay): null
    clear keyboard state: null
    close UI element: Escape
    cycle click count: null
    cycle font: null
    cycle font reverse: null
    cycle grid action level: null
    cycle mouse action type: null
    cycle mouse button: null
    decrease overlay opacity: ArrowDown
    edit config: Tab
    enter free mode: null
    enter label mode: null
    execute mouse action: Space
    execute mouse move: null
    exit free mode: Escape
    exit label mode: null
    force overlay resize: null
    forward click: null
    forward mouse button: null
    forward mouse button (w/o overlay): null
    hide overlay: Escape
    hold for back button: null
    hold for drag: null
    hold for forward button: null
    hold for free mode: null
    hold for middle button: shiftleft
    hold for move: null
    hold for right button: optionright
    hold for speed decrease:
    - shiftleft
    - e
    hold for speed increase:
    - commandleft
    - n
    increase overlay opacity: ArrowUp
    invert colors: null
    jump to bottom: null
    jump to left edge: null
    jump to right edge: null
    jump to top: null
    left click: null
    left mouse button: Space
    left mouse button (w/o overlay): null
    middle click: null
    middle mouse button: '{'
    middle mouse button (w/o overlay): null
    move down: s
    move left: r
    move right: t
    move up: f
    release hold/drag: Escape
    repeat last mouse action: null
    right click: null
    right mouse button: '}'
    right mouse button (w/o overlay): null
    show overlay: null
    subgrid nudge down: null
    subgrid nudge left: null
    subgrid nudge right: null
    subgrid nudge up: null
    switch monitor left: null
    switch monitor right: null
    toggle app enabled: null
    toggle continuous mode: null
    toggle continuous mode until closed: null
    toggle free mode:
    - F14
    - shift+F14
    toggle label mode: null
    toggle overlay:
    - F13
    - shift+F13
    toggle overlay lock: null
    undo last key: Backspace
    wheel down: h
    wheel down fast: null
    wheel left: k
    wheel left fast: null
    wheel right: .
    wheel right fast: null
    wheel step down: null
    wheel step down large: null
    wheel step left: null
    wheel step left large: null
    wheel step right: null
    wheel step right large: null
    wheel step up: null
    wheel step up large: null
    wheel up: ','
    wheel up fast: null
  name: mac
log_level: info
mac_hud_window_level: 1001
monitor_assignment_mode: auto
mouse_scaling: auto
mouse_screen_offset_scaling: auto
name: ''
overlay_scaling: auto
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.2
  background_colors:
  - - 0.0
    - 0.0
    - 0.0
    - 0.35
  bg_color_block_size: 1
  bg_color_transforms_level_1:
  - - hsla_add
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  bg_color_transforms_level_2:
  - - hsla_add
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  char_anchor: center
  char_bg_height: 1.1
  char_bg_rgba:
  - 0.02
  - 0.04
  - 0.06
  - 0.0
  char_bg_roundness: 0.25
  char_bg_width: 1.0
  char_display: all
  char_spacing_cell_width_ratio: 0.5
  char_spacing_font_size_ratio: 0.5
  char_spacing_strategy: cell_width_relative
  colorParamInput: none
  cursor_drag_rgba:
  - 0.0
  - 0.5
  - 1.0
  - 0.7
  cursor_move_rgba:
  - 0.75
  - 0.41
  - 0.92
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.7
  cursor_rgba:
  - 1.0
  - 0.54
  - 0.0
  - 0.7
  cursor_right_button_rgba:
  - 0.92
  - 0.32
  - 0.32
  - 0.7
  cursor_size: 7
  font_family: AmericanTypewriter
  font_size_multiplier: 0.5
  font_style: normal
  font_weight: 500
  free_mode_indicator_offset_x: -7.0
  free_mode_indicator_offset_y: -8.0
  free_mode_indicator_rgba:
  - 0.5803921568627451
  - 0.2980392156862745
  - 0.2980392156862745
  - 0.9
  free_mode_indicator_size: 10
  free_mode_status_display: cursor
  grid_line_style: lines
  grid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  highlight_animation_ms: 0
  highlight_rgba:
  - 0.77
  - 0.44
  - 0.15
  - 0.25
  label_align: center
  label_bg_rgba:
  - 1.0
  - 0.84
  - 0.04
  - 0.95
  label_font_size: 12
  label_text_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  name: default
  show_initial_highlight: false
  subgrid_font_size_multiplier: 0.75
  subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  subgrid_text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  text_shadow_blur_radius: 2.0
  text_shadow_offset:
  - 0.0
  - 0.0
  text_shadow_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  text_y_offset: 0.0
  toast_opacity: 0.5
  use_bg_color_transforms: false
  window_opacity: 0.9
translate_presets_to_keyboard_layout: true
