# splits
bind | split-window -h
bind - split-window -v

unbind %
unbind '"'


# kill pane binds
unbind x
bind x kill-pane

set -g focus-events on

# -n makes it so you dont need the prfix. {} special chars n the parser so we have to excape it properly
bind-key -n 'M-{' previous-window
bind-key -n 'M-}' next-window

set -g status-left-length 100
set -g status-right-length 100

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g window-status-current-format "#[fg=#3d5a3d]░▒▓#[fg=#c8e6a0,bg=#3d5a3d] #I #W #[bg=default,fg=#3d5a3d]▓▒░"
set -g window-status-format "#[fg=#9ece6a]░▒▓#[fg=#16161e,bg=#9ece6a] #I #W #[bg=default,fg=#9ece6a]▓▒░"

set -g status-left "#[fg=#000000,bold] #S #[fg=default,nobold]"
set -g status-right ""



set -g renumber-windows on
set -g status-position bottom 
set -g mouse on

set -g default-terminal "tmux-256color"
set -sg escape-time 10
set -g focus-events on

bind-key -n S-Left resize-pane -L 5
bind-key -n S-Down resize-pane -D 5
bind-key -n S-Up resize-pane -U 5
bind-key -n S-Right resize-pane -R 5
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

bind -r < swap-window -t -1 \; select-window -t -1
bind -r > swap-window -t +1 \; select-window -t +1

bind X kill-window
set -g status-right "#[bold, fg=#c8e6a0]    ✧･ﾟ: %I:%M %p :ﾟ･✧    #[default]"

set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.tmux/plugins/tpm/tpm'
